language: node_js
sudo: false
cache:
   directories:
      - $HOME/download/

node_js:
- '6'

before_install:
- mv .tools /tmp/tools/

install:
- export GOPATH="${HOME}/gocode/"
- export PATH="${HOME}/gocode/bin:$PATH"
- mkdir $HOME/download/
- [[ -e $HOME/download/ipfs.tar.gz ]] || wget -q -O $HOME/download/ipfs.tar.gz https://dist.ipfs.io/go-ipfs/v0.4.4/go-ipfs_v0.4.4_linux-amd64.tar.gz
- tar -C /tmp/ -xvf $HOME/download/ipfs.tar.gz
- /tmp/go-ipfs/ipfs init --empty-repo
- /tmp/go-ipfs/ipfs bootstrap add '/ip4/5.172.41.102/tcp/4001/ipfs/QmaEbSMwN9pWJgot9GSw5npgLengbYQU4DDwoxuHbavqjb'
- "( nohup /tmp/go-ipfs/ipfs daemon | tee /tmp/nohup.out ) &"
- npm install json -g

script: "/tmp/tools/build.sh"
