language: go
sudo: false
cache:
   directories:
      - $HOME/gocode/

node_js:
- '6'

go:
   - 1.7.3

before_install:
- mv .tools /tmp/tools/

install:
- export GOPATH="${HOME}/gocode/"
- export PATH="${HOME}/gocode/bin:$PATH"
- go get -u github.com/ipfs/ipfs-update
- "$GOPATH/bin/ipfs-update install v0.4.4"
- ipfs init --empty-repo
- ipfs bootstrap add '/ip4/5.172.41.102/tcp/4001/ipfs/QmaEbSMwN9pWJgot9GSw5npgLengbYQU4DDwoxuHbavqjb'
- "( nohup ipfs daemon | tee /tmp/nohup.out ) &"
- npm install json -g

script: "/tmp/tools/build.sh"
